use crate::utils::canonicalize_tracked_file_path;
use regex::Regex;
use std::collections::HashSet;
use std::fs;
use std::path::Path;

pub fn get_recent_failures() -> HashSet<String> {
    let mut failed_modules = HashSet::new();

    // Priority 1: FAILURE_REPORT.md (Generated by System)
    if let Ok(content) = fs::read_to_string("../../FAILURE_REPORT.md") {
        extract_failures(&content, &mut failed_modules);
    }

    // Priority 2: test_results.txt (Standard Output)
    if let Ok(content) = fs::read_to_string("../../test_results.txt") {
        extract_failures(&content, &mut failed_modules);
    }

    // Priority 3: app_test_fail.txt (Custom Hook)
    if let Ok(content) = fs::read_to_string("../../app_test_fail.txt") {
        extract_failures(&content, &mut failed_modules);
    }

    failed_modules
}

fn extract_failures(content: &str, set: &mut HashSet<String>) {
    let file_regex =
        Regex::new(r"((?:\.\./)*[a-zA-Z0-9_\-\/\.]+\.(res|rs|js|jsx|css|html))").unwrap();

    for line in content.lines() {
        if line.to_lowercase().contains("fail") || line.to_lowercase().contains("error") {
            for cap in file_regex.captures_iter(line) {
                if let Some(m) = cap.get(1) {
                    if let Some(path) = canonicalize_tracked_file_path(m.as_str()) {
                        if let Some(stem) =
                            Path::new(&path).file_stem().and_then(|value| value.to_str())
                        {
                            set.insert(stem.to_string());
                        }
                        set.insert(path);
                    }
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_failures_keeps_canonical_paths_and_file_stems_only() {
        let mut failures = HashSet::new();
        extract_failures(
            "error: ../../backend/src/auth/../../backend/src/auth/middleware.rs failed\nError Reference `src/core/SchemaDefinitions.res` for current shapes.",
            &mut failures,
        );

        assert!(failures.contains("backend/src/auth/middleware.rs"));
        assert!(failures.contains("middleware"));
        assert!(!failures.contains("Reference"));
    }
}
