/* tests/TestRunner.res */
Console.log("Starting Frontend Unit Tests...")

GeoUtilsTest.run()
SimulationSystemTest.run()
TourLogicTest.run()
PathInterpolationTest.run()
ReducerTest.run()
ReducerJsonTest.run()
SceneReducerTest.run()
HotspotReducerTest.run()
ExifParserTest.run()
SharedTypesTest.run()
ReBindingsTest.run()
BackendApiTest.run()
ProjectManagerTest.run()
ResizerTest.run()
UploadProcessorTest.run()
TeaserManagerTest.run()
TourTemplateAssetsTest.run()
TourTemplateScriptsTest.run()
TourTemplateStylesTest.run()
StateInspectorTest.run()
NavigationTest.run()
ViewerLoaderTest.run()

Console.log("All frontend tests passed successfully! 🎉")
