/* tests/TestRunner.res */
Console.log("Starting Frontend Unit Tests...")

GeoUtilsTest.run()
LoggerTest.run()
SimulationSystemTest.run()
InputSystemTest.run()
TourLogicTest.run()
PathInterpolationTest.run()
ReducerTest.run()
ReducerHelpersTest.run()
JsonTypesTest.run()
SceneReducerTest.run()
HotspotReducerTest.run()
ExifParserTest.run()
AudioManagerTest.run()
ExifReportGeneratorTest.run()
SharedTypesTest.run()
ReBindingsTest.run()
BackendApiTest.run()
ProjectManagerTest.run()
DownloadSystemTest.run()
ProjectDataTest.run()
ResizerTest.run()
UploadProcessorTest.run()
VideoEncoderTest.run()
TeaserManagerTest.run()
TeaserRecorderTest.run()
TourTemplateAssetsTest.run()
TourTemplateScriptsTest.run()
TourTemplateStylesTest.run()
TourTemplatesTest.run()
ExporterTest.run()
LazyLoadTest.run()
ProgressBarTest.run()
StateInspectorTest.run()
ServiceWorkerTest.run()
NavigationTest.run()
NavigationRendererTest.run()
MainTest.run()
ViewerLoaderTest.run()
ActionsTest.run()
GlobalStateBridgeTest.run()
RootReducerTest.run()
ProjectReducerTest.run()
NavigationReducerTest.run()
EventBusTest.run()
TimelineReducerTest.run()
SimulationNavigationTest.run()
SimulationChainSkipperTest.run()
SimulationPathGeneratorTest.run()
TeaserPathfinderTest.run()
ServerTeaserTest.run()

Console.log("All frontend tests passed successfully! 🎉")
%%raw(`process.exit(0)`)
