use crate::middleware::rate_limiter::{RateLimitResponseTransformer, RateLimiters};
use actix_governor::Governor;
use actix_web::web;

#[cfg(feature = "builder-runtime")]
use super::{media, project, project_export, project_import};

#[cfg(feature = "builder-runtime")]
pub(super) fn configure_project_api(cfg: &mut web::ServiceConfig, limiters: &RateLimiters) {
    cfg.route(
        "/save",
        web::post()
            .to(project::save_project)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/load",
        web::post()
            .to(project::load_project)
            .wrap(RateLimitResponseTransformer::new("read"))
            .wrap(Governor::new(&limiters.read)),
    )
    .route(
        "/create-tour-package",
        web::post()
            .to(project::create_tour_package)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/validate",
        web::post()
            .to(project::validate_project)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/snapshot/sync",
        web::post()
            .to(project::sync_snapshot)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/dashboard/projects",
        web::get()
            .to(project::list_dashboard_projects)
            .wrap(RateLimitResponseTransformer::new("read"))
            .wrap(Governor::new(&limiters.read)),
    )
    .route(
        "/dashboard/projects/bulk-delete",
        web::post()
            .to(project::bulk_delete_dashboard_projects)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/dashboard/projects/{session_id}",
        web::get()
            .to(project::load_dashboard_project)
            .wrap(RateLimitResponseTransformer::new("read"))
            .wrap(Governor::new(&limiters.read)),
    )
    .route(
        "/dashboard/projects/{session_id}",
        web::delete()
            .to(project::delete_dashboard_project)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/dashboard/projects/{session_id}/duplicate",
        web::post()
            .to(project::duplicate_dashboard_project)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/dashboard/projects/{session_id}/snapshots",
        web::get()
            .to(project::list_project_snapshots)
            .wrap(RateLimitResponseTransformer::new("read"))
            .wrap(Governor::new(&limiters.read)),
    )
    .route(
        "/dashboard/projects/{session_id}/snapshots/{snapshot_id}/restore",
        web::post()
            .to(project::restore_project_snapshot)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/dashboard/projects/{session_id}/snapshots/{snapshot_id}",
        web::get()
            .to(project::load_project_snapshot)
            .wrap(RateLimitResponseTransformer::new("read"))
            .wrap(Governor::new(&limiters.read)),
    )
    .route(
        "/snapshot/assets",
        web::post()
            .to(project::sync_snapshot_assets)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/cache/cleanup",
        web::post()
            .to(project::cleanup_backend_cache)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/import",
        web::post()
            .to(project_import::import_project)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/import/init",
        web::post()
            .to(project_import::import_project_init)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/import/chunk",
        web::post()
            .to(project_import::import_project_chunk)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/import/status/{upload_id}",
        web::get()
            .to(project_import::import_project_status)
            .wrap(RateLimitResponseTransformer::new("read"))
            .wrap(Governor::new(&limiters.read)),
    )
    .route(
        "/import/complete",
        web::post()
            .to(project_import::import_project_complete)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/import/abort",
        web::post()
            .to(project_import::import_project_abort)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/export/init",
        web::post()
            .to(project_export::export_init)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/export/chunk",
        web::post()
            .to(project_export::export_chunk)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/export/status/{upload_id}",
        web::get()
            .to(project_export::export_status)
            .wrap(RateLimitResponseTransformer::new("read"))
            .wrap(Governor::new(&limiters.read)),
    )
    .route(
        "/export/complete",
        web::post()
            .to(project_export::export_complete)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/export/abort",
        web::post()
            .to(project_export::export_abort)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/calculate-path",
        web::post()
            .to(project::calculate_path)
            .wrap(RateLimitResponseTransformer::new("write"))
            .wrap(Governor::new(&limiters.write)),
    )
    .route(
        "/{project_id}/file/{filename:.*}",
        web::get()
            .to(media::serve_project_file)
            .wrap(RateLimitResponseTransformer::new("read"))
            .wrap(Governor::new(&limiters.read)),
    );
}

#[cfg(not(feature = "builder-runtime"))]
pub(super) fn configure_project_api(_cfg: &mut web::ServiceConfig, _limiters: &RateLimiters) {}
