open Types

let initialState: state = {
  tourName: "Untitled Tour",
  inventory: Belt.Map.String.empty,
  sceneOrder: [],
  activeIndex: -1,
  activeYaw: 0.0,
  activePitch: 0.0,
  appMode: Initializing,
  isLinking: false,
  transition: {
    type_: Fade,
    targetHotspotIndex: -1,
    fromSceneName: None,
  },
  exifReport: None,
  linkDraft: None,
  movingHotspot: None,
  preloadingSceneIndex: -1,
  isTeasing: false,
  timeline: [],
  activeTimelineStepId: None,
  // Domain Slices
  navigationState: NavigationState.initial(),
  // isSimulationMode: false,
  simulation: {
    status: Idle,
    visitedLinkIds: [],
    stoppingOnArrival: false,
    skipAutoForwardGlobal: false,
    lastAdvanceTime: 0.0,
    pendingAdvanceId: None,
    autoPilotJourneyId: 0,
  },
  lastUsedCategory: "outdoor",
  sessionId: None,
  logo: None,
  marketingComment: "",
  marketingPhone1: "",
  marketingPhone2: "",
  marketingForRent: false,
  marketingForSale: false,
  structuralRevision: 0,
  nextSceneSequenceId: 1,
  discoveringTitleCount: 0,
  visitedScenes: [], // Scenes animate only once for better UX
}
