open Types

let initialState: state = {
  tourName: "Tour Name",
  scenes: [],
  activeIndex: -1,
  activeYaw: 0.0,
  activePitch: 0.0,
  appMode: Initializing,
  isLinking: false,
  transition: {
    type_: Fade,
    targetHotspotIndex: -1,
    fromSceneName: None,
  },
  exifReport: None,
  linkDraft: None,
  preloadingSceneIndex: -1,
  isTeasing: false,
  deletedSceneIds: [],
  timeline: [],
  activeTimelineStepId: None,
  navigation: Idle,
  navigationFsm: Idle,
  // isSimulationMode: false,
  simulation: {
    status: Idle,
    visitedScenes: [],
    stoppingOnArrival: false,
    skipAutoForwardGlobal: false,
    lastAdvanceTime: 0.0,
    pendingAdvanceId: None,
    autoPilotJourneyId: 0,
  },
  incomingLink: None,
  autoForwardChain: [],
  pendingReturnSceneName: None,
  currentJourneyId: 0,
  lastUsedCategory: "outdoor",
  sessionId: None,
}
