open Vitest
open State
open Types

describe("State", () => {
  test("initialState should have correct default values", t => {
    t->expect(initialState.tourName)->Expect.toBe("Untitled Tour")
    t->expect(initialState.activeIndex)->Expect.toBe(-1)
    t->expect(initialState.activeYaw)->Expect.toBe(0.0)
    t->expect(initialState.activePitch)->Expect.toBe(0.0)
    t->expect(initialState.isLinking)->Expect.toBe(false)
    t->expect(initialState.transition.type_)->Expect.toEqual(Fade)
    t->expect(initialState.appMode)->Expect.toEqual(Initializing)
    t->expect(initialState.exifReport)->Expect.toEqual(None)
    t->expect(initialState.linkDraft)->Expect.toEqual(None)
    t->expect(initialState.preloadingSceneIndex)->Expect.toBe(-1)
    t->expect(initialState.isTeasing)->Expect.toBe(false)
    t->expect(initialState.timeline)->Expect.toEqual([])
    t->expect(initialState.activeTimelineStepId)->Expect.toEqual(None)
    t->expect(initialState.navigationState.navigation)->Expect.toEqual(Idle)
    t->expect(initialState.simulation.status)->Expect.toEqual(Idle)
    t->expect(initialState.simulation.visitedScenes)->Expect.toEqual([])
    t->expect(initialState.simulation.stoppingOnArrival)->Expect.toBe(false)
    t->expect(initialState.simulation.skipAutoForwardGlobal)->Expect.toBe(false)
    t->expect(initialState.simulation.lastAdvanceTime)->Expect.toBe(0.0)
    t->expect(initialState.simulation.pendingAdvanceId)->Expect.toEqual(None)
    t->expect(initialState.simulation.autoPilotJourneyId)->Expect.toBe(0)
    t->expect(initialState.navigationState.incomingLink)->Expect.toEqual(None)
    t->expect(initialState.navigationState.autoForwardChain)->Expect.toEqual([])
    t->expect(initialState.pendingReturnSceneName)->Expect.toEqual(None)
    t->expect(initialState.navigationState.currentJourneyId)->Expect.toBe(0)
    t->expect(initialState.lastUsedCategory)->Expect.toBe("outdoor")
    t->expect(initialState.sessionId)->Expect.toEqual(None)
  })
})
